// Scan modules list - must stay in sync with backend transformers ALL_MODULES
export const SCAN_MODULES = [
  "status",
  "get-ip",
  "headers",
  "dns",
  "txt-records",
  "hsts",
  "robots-txt",
  "security-txt",
  "sitemap",
  "social-tags",
  "page-source",
  "ssl",
  "tls",
  "whois",
  "associated-hosts",
  "dnssec",
  "firewall",
  "cookies",
  "redirects",
  "mail-config",
  "http-security",
  "rank",
  "carbon",
  "linked-pages",
  "archives",
  "block-lists",
  "legacy-rank",
  "ports",
  "tech-stack",
  "threats",
  "trace-route",
  "screenshot",
  "features",
  "quality",
  "dns-server",
] as const;

export type ScanModuleId = (typeof SCAN_MODULES)[number];

// Batch grouping - matches backend MODULE_BATCHES
export const MODULE_BATCHES = {
  quick: [
    "status",
    "get-ip",
    "headers",
    "dns",
    "txt-records",
    "hsts",
    "robots-txt",
    "security-txt",
    "sitemap",
    "social-tags",
    "page-source",
  ] as const,
  medium: [
    "ssl",
    "tls",
    "whois",
    "associated-hosts",
    "dnssec",
    "firewall",
    "cookies",
    "redirects",
    "mail-config",
    "http-security",
    "rank",
    "carbon",
    "linked-pages",
    "archives",
    "block-lists",
    "legacy-rank",
  ] as const,
  heavy: [
    "ports",
    "tech-stack",
    "threats",
    "trace-route",
    "screenshot",
    "features",
    "quality",
    "dns-server",
  ] as const,
} as const;

// Human-readable labels for display
export const SCAN_MODULE_LABELS: Record<string, string> = {
  status: "HTTP Status",
  "get-ip": "IP Info",
  headers: "Headers",
  dns: "DNS Records",
  "txt-records": "TXT Records",
  hsts: "HSTS",
  "robots-txt": "Robots.txt",
  "security-txt": "Security.txt",
  sitemap: "Sitemap",
  "social-tags": "Social Tags",
  "page-source": "Page Source",
  ssl: "SSL",
  tls: "TLS",
  whois: "WHOIS",
  "associated-hosts": "Associated Hosts",
  dnssec: "DNSSEC",
  firewall: "Firewall",
  cookies: "Cookies",
  redirects: "Redirects",
  "mail-config": "Email Config",
  "http-security": "HTTP Security",
  rank: "Ranking",
  carbon: "Carbon",
  "linked-pages": "Linked Pages",
  archives: "Archives",
  "block-lists": "Block Lists",
  "legacy-rank": "Legacy Rank",
  ports: "Ports",
  "tech-stack": "Tech Stack",
  threats: "Threats",
  "trace-route": "Traceroute",
  screenshot: "Screenshot",
  features: "Features",
  quality: "Quality",
  "dns-server": "DNS Server",
};
