"""Add celery_task_id column to scans table.

Revision ID: celery_task_id_on_scans
Revises: initial_scan_schema
Create Date: 2026-03-16 11:23:36.123592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "celery_task_id_on_scans"
down_revision: Union[str, None] = "initial_scan_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'celery_task_id')
    # ### end Alembic commands ###
